[package]
name = "test-module"
version = "0.1.0"
authors = ["rca <raphael.catolino@gmail.com>"]

[dependencies]
pamsm = { path = "../", features = ["libpam"] }
rand = "0.8"

[lib]
crate-type = ["cdylib"]
