[package]
name = "test-module"
version = "0.1.0"
authors = ["rca <raphael.catolino@gmail.com>"]

[dependencies]
time = "^0.2"
pamsm = { path = "../", features = ["libpam"] }

[lib]
crate-type = ["cdylib"]
