language: rust

rust:
  - 1.32.0  # minimum supported toolchain
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - CLIPPY_RUST_VERSION=1.32.0

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      rustup component add clippy-preview;
    fi'

script:
  - cargo test --all-features
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      cargo clippy --all-features -- -D warnings;
    fi'
